/**
 * Test: Cache Match Must Also Match Model
 *
 * This test verifies that cached prompts are correctly filtered by model.
 * A cache entry for one model cannot be reused for a different model,
 * since KV cache is architecture-specific.
 *
 * Key Insight: KV cache is generated by a specific model's architecture.
 * - Different tokenization schemes
 * - Different internal representations
 * - Different layer structures
 */

const { BackendSelector } = require('../../backend-selector');

/**
 * Create a mock backend with cache behavior
 */
const createMockBackend = (url, healthy, priority, models, maxConcurrency = 1, cacheData = {}) => ({
  url,
  healthy,
  priority: priority || 0,
  activeRequestCount: 0,
  maxConcurrency,
  getApiTypes: () => ['openai'],
  getModels: () => models || [],
  /**
   * Mock cache matching - must match BOTH prompt AND model
   */
  findCacheMatch: (prompt, model) => {
    if (cacheData[prompt] && cacheData[prompt].model === model) {
      return {
        entry: cacheData[prompt],
        similarity: cacheData[prompt].similarity,
        matchType: 'similarity'
      };
    }
    return null;
  }
});

describe('BackendSelector - Cache Model Matching', () => {
  let selector;

  beforeEach(() => {
    selector = new BackendSelector();
  });

  describe('selectBackendWithCache() - Model must match cache entry', () => {
    it('should NOT use cache from different model - request goes to backend with no cache', () => {
      /**
       * Scenario:
       * - Backend 1 has cached "write a story" for model "llama3"
       * - Request arrives for model "qwen2.5" with prompt "write a story"
       * - Backend 2 has no cache but supports "qwen2.5"
       *
       * Expected: Backend 2 should be selected (cache doesn't match model)
       */
      const backends = [
        createMockBackend('http://cache-backend:11434', true, 1, ['llama3'], 1, {
          'write a story': { model: 'llama3', similarity: 0.95 }
        }),
        createMockBackend('http://qwen-backend:11434', true, 2, ['qwen2.5'], 1, {})
      ];

      const result = selector.selectBackendWithCache(
        backends,
        { modelString: 'qwen2.5' },
        'write a story'
      );

      // Cache on Backend 1 is for "llama3", not "qwen2.5"
      // So no cache hit - should select Backend 2 which supports qwen2.5
      expect(result.backend.url).toBe('http://qwen-backend:11434');
      expect(result.status).toBe('found');
    });

    it('should use cache only when model matches exactly', () => {
      /**
       * Scenario:
       * - Backend 1 has cached "write a story" for model "llama3"
       * - Request arrives for model "llama3" with prompt "write a story"
       *
       * Expected: Backend 1 should be selected (cache matches model)
       */
      const backends = [
        createMockBackend('http://cache-backend:11434', true, 1, ['llama3'], 1, {
          'write a story': { model: 'llama3', similarity: 0.95 }
        }),
        createMockBackend('http://no-cache:11434', true, 2, ['llama3'], 1, {})
      ];

      const result = selector.selectBackendWithCache(
        backends,
        { modelString: 'llama3' },
        'write a story'
      );

      // Cache matches both prompt AND model
      expect(result.backend.url).toBe('http://cache-backend:11434');
      expect(result.status).toBe('found');
    });

    it('should not cache match when same prompt cached for multiple models', () => {
      /**
       * Scenario:
       * - Backend 1 has same prompt cached for BOTH "llama3" and "qwen2.5"
       * - Request arrives for "llama3"
       *
       * Expected: Backend 1 should be selected (llama3 cache exists)
       */
      const backends = [
        createMockBackend('http://multi-cache:11434', true, 1, ['llama3', 'qwen2.5'], 1, {
          'write a story': { model: 'llama3', similarity: 0.95 }
        }),
        createMockBackend('http://no-cache:11434', true, 2, ['llama3'], 1, {})
      ];

      const result = selector.selectBackendWithCache(
        backends,
        { modelString: 'llama3' },
        'write a story'
      );

      // The cache entry has model='llama3', so it matches
      expect(result.backend.url).toBe('http://multi-cache:11434');
    });

    it('should select by priority when no cache matches (regardless of backend cache)', () => {
      /**
       * Scenario:
       * - Backend 1 has cache for "llama3" but request is for "qwen2.5"
       * - Backend 2 has no cache but supports "qwen2.5" and has higher priority
       *
       * Expected: Backend 2 selected (no cache hit, priority-based selection)
       */
      const backends = [
        createMockBackend('http://low-prio:11434', true, 1, ['llama3'], 1, {
          'write a story': { model: 'llama3', similarity: 0.95 }
        }),
        createMockBackend('http://high-prio:11434', true, 5, ['qwen2.5'], 1, {})
      ];

      const result = selector.selectBackendWithCache(
        backends,
        { modelString: 'qwen2.5' },
        'write a story'
      );

      // Backend 1's cache doesn't match "qwen2.5"
      // Backend 2 selected by priority (highest priority, no cache hit)
      expect(result.backend.url).toBe('http://high-prio:11434');
    });

    it('should not match cache when model string is null', () => {
      /**
       * Scenario:
       * - Backend 1 has cache for "write a story"
       * - Request has no model string
       *
       * Expected: No cache lookup performed, falls back to priority selection
       */
      const backends = [
        createMockBackend('http://cache-backend:11434', true, 1, ['llama3'], 1, {
          'write a story': { model: 'llama3', similarity: 0.95 }
        }),
        createMockBackend('http://no-cache:11434', true, 5, ['llama3'], 1, {})
      ];

      const result = selector.selectBackendWithCache(
        backends,
        { modelString: null },
        'write a story'
      );

      // No model string means no cache data available
      expect(result.backend.url).toBe('http://no-cache:11434'); // Higher priority
      expect(result.status).toBe('found');
    });

    it('should handle model mismatch when backend supports multiple models', () => {
      /**
       * Scenario:
       * - Backend 1 supports both "llama3" and "qwen2.5"
       * - Backend 1 has cache only for "llama3" version of prompt
       * - Request is for "qwen2.5" with same prompt
       *
       * Expected: No cache hit - Backend 2 selected (or Backend 1 by priority)
       */
      const backends = [
        createMockBackend('http://multi-model:11434', true, 1, ['llama3', 'qwen2.5'], 1, {
          'write a story': { model: 'llama3', similarity: 0.95 }
        }),
        createMockBackend('http://other:11434', true, 2, ['qwen2.5'], 1, {})
      ];

      const result = selector.selectBackendWithCache(
        backends,
        { modelString: 'qwen2.5' },
        'write a story'
      );

      // Cache entry has model='llama3', request is for 'qwen2.5'
      // No cache hit, so backend selection based on availability/priority
      // Backend 1 is at max concurrency (activeRequestCount defaults to 0, maxConcurrency=1)
      // Should select Backend 2 which has no cache constraints
      expect(result.backend.url).toBe('http://other:11434');
    });
  });
});